[build]
  command = "npm run netlify-build"
  publish = "dist/atjhub-0.1-cursor"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SUPABASE_URL = "from_netlify_env"
  SUPABASE_ANON_KEY = "from_netlify_env"
  ADMIN_PASSWORD_HASH = "from_netlify_env"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development" 