backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", default: "/images/default-project.jpg"}
      - {label: "Project URL", name: "url", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss"}

  - name: "profile"
    label: "Profile"
    folder: "_data"
    create: false
    files:
      - file: "_data/profile.yml"
        label: "Profile Information"
        name: "profile"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Bio", name: "bio", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Avatar", name: "avatar", widget: "image", default: "/images/avatar.jpg"}
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - {label: "GitHub", name: "github", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "Portfolio", name: "portfolio", widget: "string", required: false}

  - name: "site_settings"
    label: "Site Settings"
    folder: "_data"
    create: false
    files:
      - file: "_data/settings.yml"
        label: "Site Configuration"
        name: "settings"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Contact Email", name: "contact_email", widget: "string"}
          - {label: "Formspree Form ID", name: "formspree_id", widget: "string"}
          - label: "Theme Colors"
            name: "theme"
            widget: "object"
            fields:
              - {label: "Primary Color", name: "primary", widget: "string", default: "#3b82f6"}
              - {label: "Secondary Color", name: "secondary", widget: "string", default: "#8b5cf6"}
              - {label: "Background Color", name: "background", widget: "string", default: "#0f172a"}

  - name: "pages"
    label: "Pages"
    folder: "_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss"} 